use project;
--task3--
SELECT MAX(SALARY) FROM EMPLOYEES WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEES);


SELECT * FROM SALARIES;



--task4--
SELECT WORK_DEPT ,COUNT(*) FROM EMPLOYEES GROUP BY WORK_DEPT;
SELECT COUNT(*) FROM EMPLOYEES GROUP BY WORK_DEPT;


--join operations--
SELECT EMPLOYEES.PK_EMPLOYEEID,EMPLOYEES.FIRST_NAME,EMPLOYEES.LAST_NAME ,SALARIES.GROSS 
FROM EMPLOYEES INNER JOIN SALARIES ON EMPLOYEES.PK_EMPLOYEEID=SALARIES.FK_EMPLOYEEID;

SELECT EMPLOYEES.PK_EMPLOYEEID,EMPLOYEES.FIRST_NAME,EMPLOYEES.LAST_NAME ,SALARIES.GROSS 
FROM EMPLOYEES RIGHT JOIN SALARIES ON EMPLOYEES.PK_EMPLOYEEID=SALARIES.FK_EMPLOYEEID;


SELECT * FROM SALARIES RIGHT JOIN EMPLOYEES ON EMPLOYEES.PK_EMPLOYEEID=SALARIES.FK_EMPLOYEEID;

SELECT * FROM EMPLOYEES LEFT JOIN SALARIES ON EMPLOYEES.PK_EMPLOYEEID=SALARIES.FK_EMPLOYEEID;


--task6--
SELECT EMPLOYEES.SALARY,EMPLOYEES.FIRST_NAME,EMPLOYEES.LAST_NAME ,SALARIES.GROSS 
FROM EMPLOYEES JOIN SALARIES ON EMPLOYEES.PK_EMPLOYEEID=SALARIES.FK_EMPLOYEEID;



